name: Hello World                      # ワークフローの名前
on: push                               # ワークフローのトリガー(今回はpush) 
                                       # [on, pull_request]のように複数指定も可能

jobs:                                  # ジョブの定義
  hello-world-job:                     # ジョブの名前
    runs-on: ubuntu-latest             # ジョブが実行されるランナーの環境
    steps:                             # ジョブのステップの定義
      - name: Checkout repository      # ステップの名前
        uses: actions/checkout@v4      # GitHub Actionsのアクションを使用
      - name: Hello World              # ステップの名前
        run: echo "Hello World"        # ステップの実行内容(Hello Worldを出力)
      - name: Hello World              # 複数行実行
        run: |
            echo "Hello"
            echo "World"